### ISSUE TITLE
URL example in readme is incorrect

### ISSUE THREAD

**Issue by ajsharp** [pedro/heroku-mongo-sync#1]
From the readme: export MONGO_URL = mongo://user:pass@localhost:1234/db

Should be export MONGO_URL = mongodb://user:pass@localhost:1234/db

Re: http://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/connection.rb#L34

Thanks for the plugin.

**Comment by erichurst** [comment]
I would also add that the spacing around the '=' should be removed. It would read:

export MONGO_URL=mongodb://user:pass@localhost:1234/db

The spacing results in an invalid identifier error on the assignment operator.

**Comment by pedro** [comment]
Hey guys, 

So sorry for dropping the ball here. In case you still have any interest please refer to Marco's fork, he's maintaining this plugin now:
https://github.com/marcofognog/heroku-mongo-sync

Thanks
