### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by jasonkuhrt** [pedro/heroku-mongo-sync#10]
```
ϟ heroku mongo:push                                                                                                      master [bfd2b91]
 !    DEPRECATED: Heroku::Client#deprecate is deprecated, please use the heroku-api gem.
 !    DEPRECATED: More information available at https://github.com/heroku/heroku.rb
 !    DEPRECATED: Deprecated method called from /Users/jasonkuhrt/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/heroku-2.31.1/lib/heroku/client.rb:129.
THIS WILL REPLACE ALL DATA for vanyarose ON flame.mongohq.com WITH localhost
Are you sure? (y/n) n
```

Something similar to https://github.com/ddollar/heroku-accounts/issues/37 perhaps?

**Comment by cggaurav** [comment]
Similar error while it goes into an unfinished loop w/o updating remoteDB.

!    DEPRECATED: Heroku::Client#deprecate is deprecated, please use the heroku-api gem.
 !    DEPRECATED: More information available at https://github.com/heroku/heroku.rb
 !    DEPRECATED: Deprecated method called from /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/heroku-2.31.2/lib/heroku/client.rb:129.
THIS WILL REPLACE ALL DATA for gs ON mongodb://heroku:17810bfb41b513ffd9ceae11232a4da3@vincent.mongohq.com:10064/app7264828 WITH gs
Are you sure? (y/n) y
 !    DEPRECATED: Heroku::Client#deprecate is deprecated, please use the heroku-api gem.
 !    DEPRECATED: More information available at https://github.com/heroku/heroku.rb
 !    DEPRECATED: Deprecated method called from /Users/cggaurav/.rvm/gems/ruby-1.9.3-p194/gems/heroku-2.31.2/lib/heroku/client.rb:129.
Syncing users: 504 of 784 (64.29%)...

**Comment by majioa** [comment]
!    DEPRECATED: Heroku::Client#deprecate is deprecated, please use the heroku-api gem.
 !    DEPRECATED: More information available at https://github.com/heroku/heroku.rb
 !    DEPRECATED: Deprecated method called from /usr/local/rvm/gems/ruby-1.9.3-rc1@.../gems/heroku-2.30.3/lib/heroku/client.rb:129.

**Comment by exceptionraiser** [comment]
I'm also getting a whole slew of deprecation warnings:

```
**Notice: C extension not loaded. This is required for optimum MongoDB Ruby driver performance.
  You can install the extension as follows:
  gem install bson_ext

  If you continue to receive this message after installing, make sure that the
  bson_ext gem is in your load path and that the bson_ext and mongo gems are of the same version.

 !    DEPRECATED: Heroku::Client#deprecate is deprecated, please use the heroku-api gem.
 !    DEPRECATED: More information available at https://github.com/heroku/heroku.rb
 !    DEPRECATED: Deprecated method called from /Users/ericc/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/heroku-2.32.14/lib/heroku/client.rb:129.
Replacing the earthaid db at localhost with eko.mongohq.com
 !    DEPRECATED: Heroku::Client#deprecate is deprecated, please use the heroku-api gem.
 !    DEPRECATED: More information available at https://github.com/heroku/heroku.rb
 !    DEPRECATED: Deprecated method called from /Users/ericc/.rbenv/versions/1.9.3-p194/lib/ruby/gems/1.9.1/gems/heroku-2.32.14/lib/heroku/client.rb:129.
```

Any word?

**Comment by alexslade** [comment]
Same here

**Comment by tbbooher** [comment]
agree here, as well as: Error:       Failed to authenticate user 'heroku' on db

**Comment by cggaurav** [comment]
I think we need an updated sync with the new heroku-api gem. Anyone up for it?

**Comment by marcofognog** [comment]
Abandoned project?

**Comment by pedro** [comment]
Hey guys, 

Yes, sorry about this – definitely haven't been updating this project.
If anyone wants to take a stab at fixing this please go for it and I'll merge the pull.
Let me know too if you would like to take ownership of this plugin.

**Comment by marcofognog** [comment]
Hey guys, I've got rid of this issue, in my fork at https://github.com/marcofognog/heroku-mongo-sync . Also, if you have any other issues you should report it there.

**Comment by pedro** [comment]
Excellent! Looks pretty good to me. I'm closing this project down in favor of Marco's fork.
Thank you guys.
