### ISSUE TITLE
heroku plugin installtion instruction needs a small fix

### ISSUE THREAD

**Issue by tchklovski** [pedro/heroku-mongo-sync#2]
README.md needs http: -> git: :
    - heroku plugins:install http://github.com/pedro/heroku-mongo-sync.git
    + heroku plugins:install git://github.com/pedro/heroku-mongo-sync.git

**Comment by deckchairhq** [comment]
Also, mine requires there to be quotes around the url. Rails3 - YMMV

**Comment by pedro** [comment]
Hey guys, 

So sorry for dropping the ball here. In case you still have any interest please refer to Marco's fork, he's maintaining this plugin now:
https://github.com/marcofognog/heroku-mongo-sync

Thanks
