### ISSUE TITLE
error: "Install the Mongo gem to use mongo commands:"

### ISSUE THREAD

**Issue by jasonkuhrt** [pedro/heroku-mongo-sync#9]
When I try

```
heroku mongo:pull
```

I get an error

```
 !    Install the Mongo gem to use mongo commands:
 !    sudo gem install mongo
```

Even if I do `sudo gem install mongo`, the error remains. I've tried reloading shell, etc.

Suggestions? Thanks

**Comment by jasonkuhrt** [comment]
And it seems that I have `mongo` just fine:

```
irb(main):002:0> require 'mongo'
=> true
```

**Comment by jasonkuhrt** [comment]
@pedro Any thoughts?

**Comment by pedro** [comment]
Hi Jason, 

Sorry I haven't been updating this for a long time now. Looking at the implementation it seems like we throw when `require "mongo"` raises a `LoadError`. I'd try removing that rescue clause and take a look at the original exception.

You can play with the plugin on your local machine by editing it under `~/.heroku/plugins/heroku-mongo-sync`.

Hope this helps!

Thanks,
Pedro

**Comment by jasonkuhrt** [comment]
Hey @pedro thanks for the tips. I'm currently looking at my ruby version. Based on this https://github.com/ricardochimal/taps/issues/92 I am going to try Ruby 1.9.2-p290. I'll post what I discover as I debug this problem.

**Comment by jasonkuhrt** [comment]
Disregard the above link. I continued to this one: https://github.com/heroku/heroku/issues/69 and discovered that the same problems that caused the Taps load error also cause problems for @pedro's mongo plugin. SO... the solution is to ditch the heroku toolbelt and instead use `gem install heroku` (I am using rbenv).

**Comment by pedro** [comment]
Great find! Thanks Jason.

**Comment by holgersindbaek** [comment]
I'm also getting this error after switching to the Heroku Toolbelt. Is the solution really still to ditch the heroku tool belt? Shouldn't it rather work for the Heroku Toolbelt?

Heroku gives me a deprecation warning when installing heroku by gem:

```
The `heroku` gem has been deprecated and replaced with the Heroku Toolbelt.
```

**Comment by holgersindbaek** [comment]
I ended up reverting to the heroku gem and doing gem install mongo, NOT sudo gem install mongo. Then it worked.

**Comment by nicksergeant** [comment]
What's the end game here? When the `heroku` gem no longer exists, is there a way we can keep this working?

**Comment by t0t** [comment]
Same not solved problem here. :(

**Comment by pedro** [comment]
Hey folks!

Can you try using this instead?
https://github.com/pedro/heroku-mongo-sync

I've given Marco this plugin since I stopped working on Mongo-related stuff. A lot has improved since then!

**Comment by pedro** [comment]
DOH, wrong link :}

https://github.com/marcofognog/heroku-mongo-sync
